- yield-curves/yield_curves/yield_curves/clean_yield_curves.py
Clean yield curves so that they can be used in a nice format. This includes:
- Read data from excel into pandas dataframe
- Clean data
- Unpivot data to have rates in one column
> feature: Add clean yield curves functions

- .vscode/extensions.json
- CONTRIBUTING.md
- yield-curves/requirements.txt
- yield-curves/setup.py
Write a contribution guide describing agreed norms (semantic commit messages, docstrings, ...). Add `requirements.txt` with dependencies and `setup.py` with package metadata. Define list of recommended extensions.
> build: Configure package and write contribution guide

- .vscode/extensions.json
- .vscode/settings.json
- azure-function/requirements.txt
Extend settings so that Azure Functions can be deployed (configuration automatically added by VS Code Azure Function extension).
> build: Deploy Azure Functions

- .gitignore
- local.settings.json
- yield-curves/main.py
- yield-curves/yield_curves/extraction/__init__.py
- yield-curves/yield_curves/extraction/clean_yield_curves.py
- yield-curves/yield_curves/extraction/write_to_table.py
Write the function that writes data to table storage. Create end-to-end run (download, extract, write) for one date in `main.py`.
> feature: Write data to Azure Table Storage

- .github/workflows/ci.yml
- yield-curves/requirements.txt
- yield-curves/yield_curves/tests/test_clean_yield_curves.py
Create ci.yml to configure git action for building package
> build: Configure GitHub Actions for building package

- react-app/src/App.tsx
- react-app/src/views/Home.tsx
Create a home page with title and feature sections
> feature: Create home page with title and feature sections

- react-app/src/App.tsx
- react-app/src/components/Alert/Alert.tsx
- react-app/src/components/Subscribe/Subscribe.tsx
Create a section to capture e-mail of potential prospective clients.
> feature: Create e-mail section

- react-app/src/App.tsx
- react-app/src/components/Pricing/Pricing.tsx
Create a React component displaying the pricing options. The feature section is split into smaller components and parametrized so that it's easier to update the content.
> feature: Pricing section

- react-app/package-lock.json
- react-app/package.json
- react-app/public/index.html
- react-app/src/App.tsx
- react-app/src/index.tsx
- react-app/src/views/Home.tsx
Set up routing using `react-router` and `react-router-dom` so that subpages can have their own views.
> build: Set up routing

- react-app/src/components/Feature/Feature.tsx
- react-app/src/components/Notification/Notification.tsx
- react-app/src/components/Subscribe/Subscribe.tsx
- react-app/src/components/Widgets/YieldCurveWidget.tsx
- react-app/src/views/Home.tsx
Change color from default tailwindui theme (indigo) to teal. Styling all buttons, titles, links and chart & hiding the nav bar.
> style: Customize color theme and layout

- yield-curves/main.py
- yield-curves/yield_curves/extraction/__init__.py
- yield-curves/yield_curves/extraction/clean_yield_curves.py
- yield-curves/yield_curves/tests/test_clean_yield_curves.py
Write code to extract all files and push them to table storage.
> feature: Bulk extraction

- react-app/src/components/MonthPicker/MonthPicker.tsx
Update the date range for month picker to be bwteen 2016 Jan and last month
> fix: Update the date range for month picker

- react-app/public/index.html
To be able to use Google Search Console, the site onwer needs to be verified. One way to verify it is to add a verification code into the meta tag.
> feature: Enable Google Search Console

- react-app/src/components/SelectMenu/SelectMenu.tsx
Add Google event tracker for monitoring downloading by users
> feature: Add Google event track for download button

- react-app/public/index.html
- react-app/src/components/SelectMenu/SelectMenu.tsx
- react-app/src/views/Home.tsx
Add additional information(draft) into the index.html to use the property from schema.org and change the titles to be more specific.  This is for Google to understand the site better.
> feature: Add structured data into website

- react-app/src/App.tsx
- react-app/src/components/Alert/index.ts
- react-app/src/components/Charts/index.ts
- react-app/src/components/DownloadSection/DownloadSection.tsx
- react-app/src/components/DownloadSection/index.ts
- react-app/src/components/Feature/index.ts
- react-app/src/components/Layout/index.ts
- react-app/src/components/MonthPicker/index.ts
- react-app/src/components/Notification/Notification.tsx
- react-app/src/components/Notification/index.ts
- react-app/src/components/Pricing/index.ts
- react-app/src/components/Subscribe/SubscriptionSection.tsx
- react-app/src/components/Subscribe/index.ts
- react-app/src/components/Utils/Transition.tsx
- react-app/src/components/Utils/index.ts
- react-app/src/components/Widgets/YieldCurveWidget.tsx
- react-app/src/components/Widgets/index.ts
- react-app/src/types/index.ts
- react-app/src/utils/useFetch.ts
- react-app/src/views/Home.tsx
- react-app/src/views/Playground.tsx
When fetching data from API, the same steps are regularly applied: Use fetch function, check status code, extract json and catch & log errors. All that in an async useEffect hook. Instead of writing the code repeatedly, the useFetch hook does all these steps.
> refactor: Write custom fetch hook

- .vscode/settings.json
- react-app/package-lock.json
- react-app/src/components/DownloadSection/DownloadSection.tsx
- react-app/src/components/Pricing/Price.tsx
- react-app/src/components/Pricing/PricingCard.tsx
- react-app/src/components/Pricing/PricingCardBudget.tsx
- react-app/src/components/Pricing/PricingCardMain.tsx
- react-app/src/components/Pricing/PricingCardProps.ts
- react-app/src/components/Pricing/PricingCardTop.tsx
- react-app/src/components/Pricing/PricingSection.tsx
- react-app/src/components/Subscribe/SubscriptionSection.tsx
- react-app/src/views/Home.tsx
Create a section for the subscriptions & pricing. Currently there are three tiers: free, individual and enterprise.
> feature: Add pricing section for services

- scripts/clean-insurer-list.ipynb
Write script to clean the insurer list
> feature: Clean insurer list in notebook

- .vscode/settings.json
- azure-function/curve-extraction/__init__.py
- azure-function/curve-extraction/function.json
- azure-function/curve-extraction/readme.md
- react-app/src/views/Home.tsx
- yield-curves/local.settings.template.json
- yield-curves/main.py
- yield-curves/yield_curves/extraction/clean_yield_curves.py
- yield-curves/yield_curves/extraction/download_yield_curve.py
- yield-curves/yield_curves/extraction/write_to_table.py
To schedule a run of the yield curve download, extraction & storage this pull request introduces a time-triggered Azure Function. It will run on the second day of each month, extract the Excel file and store the cleaned yield curves on Table Storage.
> build: Time-triggered Azure Function for automatic yield curve extraction

- react-app/package-lock.json
- react-app/package.json
- react-app/src/components/Button/Button.tsx
- react-app/src/components/Button/index.ts
- react-app/src/components/DownloadSection/DownloadSection.tsx
- react-app/src/components/Feature/FeatureListItem.tsx
- react-app/src/components/Feature/FeatureSection.tsx
- react-app/src/components/Pricing/PricingCard.tsx
- react-app/src/components/Subscribe/SubscriptionSection.tsx
- react-app/src/components/Widgets/YieldCurveWidget.tsx
- react-app/src/views/Home.tsx
Apply teal-blue gradients to buttons & boxes and refactor buttons into a component.
> style: Apply tailwindcss gradients to buttons & boxes

- azure-function/local.settings.template.json
- azure-function/register/__init__.py
- azure-function/requirements.txt
Send a notification when a user registers.
> feature: Notify when user register
